-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- ************************************** Sequence_1
CREATE SEQUENCE Sequence_1
START WITH 1
INCREMENT BY 1;
