-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- **************************************  Tag_1
CREATE TAG Tag_1;
