-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- ************************************** DynamicTable_2
CREATE DYNAMIC TABLE DynamicTable_2
TARGET_LAG = 'DOWNSTREAM'
  AS -- Please write SELECT logic here;
