-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- ************************************** function
CREATE FUNCTION function()
Returns -- Please specify return type
Language -- Please specify function language

  Comment = 'No Comment Provided'

AS
'-- Please provide function definition'
;
