-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: CompleteDB by damian.attademo+ep@sqldbm.com **

-- ************************************** supermarket_core.shops
CREATE HYBRID TABLE supermarket_core.shops
(
 shop_id      int NOT NULL,
 region_id    int NOT NULL,
 shop_name    varchar(200),
 address      varchar(500),
 phone        varchar(50),
 email        varchar(100),
 opening_date date,
 shop_size    decimal(10,2),

 CONSTRAINT PK_shops PRIMARY KEY ( shop_id ),
 CONSTRAINT FK_shops_regions FOREIGN KEY ( region_id ) REFERENCES supermarket_core.regions ( region_id )
);
