-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- ************************************** MaterializedView_2
CREATE MATERIALIZED VIEW MaterializedView_2
AS
-- Please write SELECT logic here;

