-- ************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Test hybTable by damian.attademo+ep@sqldbm.com *

-- ************************************** View_1
CREATE VIEW View_1
AS
-- Please write SELECT logic here;

