-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: CompleteDB by damian.attademo+ep@sqldbm.com **

-- ************************************** supermarket_core.countries
CREATE TABLE supermarket_core.countries
(
 country_id   int NOT NULL,
 country_name varchar(100),
 country_code char(2),
 currency     varchar(50),

 CONSTRAINT PK_countries PRIMARY KEY ( country_id )
);
