-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: CompleteDB by damian.attademo+ep@sqldbm.com **

-- ************************************** supermarket_core.regions
CREATE TABLE supermarket_core.regions
(
 region_id   int NOT NULL,
 country_id  int NOT NULL,
 region_name varchar(100),

 CONSTRAINT PK_regions PRIMARY KEY ( region_id ),
 CONSTRAINT FK_regions_countries FOREIGN KEY ( country_id ) REFERENCES supermarket_core.countries ( country_id )
);
