-- ************************** SqlDBM: Snowflake *************************
-- ****** Generated by SqlDBM: DP1 by damian.attademo+ep@sqldbm.com *****

-- ************************************** table_1
CREATE TABLE table_1
(
 c1 boolean NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( c1 )
);
